Repository sympa-community/sympa, pull requests merged in 2018-07, with the labels that each got.

#357 Use rsa-sha256 for DKIM signatures
  src/lib/Sympa/Message.pm
Labels: enhancement, security

#367 Fix SQL query to fetch all lists of a family
  src/lib/Sympa/List.pm
Labels: bug

#369 Introducing external js color picker plugin
  default/web_tt2/css.tt2
  default/web_tt2/head_javascript.tt2
  default/web_tt2/head_ui.tt2
  default/web_tt2/skinsedit.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/ConfDef.pm
  www/Makefile.am
  www/icons/crosshairs.png
  www/icons/h.png
  www/icons/position.png
  www/icons/sv.png
  www/js/jquery-minicolors/jquery.minicolors.css
  www/js/jquery-minicolors/jquery.minicolors.js
  www/js/jquery-minicolors/jquery.minicolors.min.js
  www/js/jquery-minicolors/jquery.minicolors.png
  www/js/sympa.js
Labels: enhancement

#377 Improve performance of purge operation
  src/lib/Sympa/Request/Handler/close_list.pm
  src/lib/Sympa/Task.pm
Labels: enhancement

#379 Styles for help contents are broken.
  default/web_tt2/css.tt2
  default/web_tt2/help.tt2
  default/web_tt2/info.tt2
Labels: bug

#380 WWSympa: Rendering bug with IE
  default/web_tt2/css.tt2
Labels: bug
