Repository sympa-community/sympa, pull requests merged in 2018-10, with the labels that each got.

#421 Create ${expldir}/${robot} directory if it does not exists
  src/lib/Sympa/List.pm
Labels: bug

#427 CSS cannot be updated if css.tt2 was older than previously generated CSS.
  src/lib/Sympa/WWW/Tools.pm
Labels: bug

#424 Refactoring and repairing login form
  default/Makefile.am
  default/mail_tt2/report.tt2
  default/web_tt2/including_lists.tt2
  default/web_tt2/login.tt2
  default/web_tt2/login_menu.tt2
  default/web_tt2/loginrequest.tt2
  default/web_tt2/main.tt2
  default/web_tt2/my.tt2
  default/web_tt2/notice.tt2
  default/web_tt2/renewpasswd.tt2
  default/web_tt2/sso_login.tt2
  default/web_tt2/user_menu.tt2
  po/sympa/POTFILES.in
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/DatabaseDescription.pm
  src/lib/Sympa/DatabaseDriver/ODBC.pm
  src/lib/Sympa/DatabaseDriver/Oracle.pm
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/WWW/Session.pm
  www/js/sympa.js
Labels: bug

#431 Oracle: Make db_name parameter allow net service name or connection identifier along with SID
  src/lib/Conf.pm
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/DatabaseDriver.pm
  src/lib/Sympa/DatabaseDriver/MySQL.pm
  src/lib/Sympa/DatabaseDriver/Oracle.pm
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/ListDef.pm
  src/lib/Sympa/Scenario.pm
Labels: enhancement

#439 Add support for TLSv1.3
  src/bin/sympa_test_ldap.pl.in
  src/lib/Conf.pm
  src/lib/Sympa/ListDef.pm
  src/lib/Sympa/ListOpt.pm
  src/libexec/ldap_alias_manager.pl.in
Labels: enhancement, security

#394 Refactoring task_manager.pl
  Makefile.am
  default/Makefile.am
  default/global_task_models/expire_bounce.daily.task
  default/global_task_models/process_bouncers.weekly.task
  default/tasks/chk_cert_expiration.daily.task
  default/tasks/crl_update.daily.task
  default/tasks/eval_bouncers.daily.task
  default/tasks/expire.2month.task
  default/tasks/expire.3month.task
  default/tasks/expire.4month.task
  default/tasks/expire.6month.task
  default/tasks/expire.9month.task
  default/tasks/expire.yearly.task
  default/tasks/expire_bounce.daily.task
  default/tasks/process_bouncers.weekly.task
  default/tasks/purge_logs_table.daily.task
  default/tasks/purge_one_time_ticket_table.daily.task
  default/tasks/purge_orphan_bounces.monthly.task
  default/tasks/purge_session_table.daily.task
  default/tasks/purge_spools.daily.task
  default/tasks/purge_tables.daily.task
  default/tasks/purge_user_table.monthly.task
  default/tasks/remind.2month.task
  default/tasks/remind.3month.task
  default/tasks/remind.4month.task
  default/tasks/remind.6month.task
  default/tasks/remind.9month.task
  default/tasks/remind.monthly.task
  default/tasks/remind.yearly.task
  default/tasks/sync_include.ttl.task
  doc/sympa_toc.pod
  po/sympa/Makefile.in.in
  po/sympa/POTFILES.in
  po/sympa/cs.po
  po/sympa/et.po
  po/sympa/fr.po
  src/cgi/wwsympa.fcgi.in
  src/lib/Makefile.am
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/Internals/Workflow.pod
  src/lib/Sympa/List.pm
  src/lib/Sympa/ListDef.pm
  src/lib/Sympa/Request/Handler/close_list.pm
  src/lib/Sympa/Request/Handler/move_list.pm
  src/lib/Sympa/Request/Handler/open_list.pm
  src/lib/Sympa/Spindle/ProcessTask.pm
  src/lib/Sympa/Spool/Task.pm
  src/lib/Sympa/Task.pm
  src/lib/Sympa/Tools/Time.pm
  src/lib/Sympa/Upgrade.pm
  src/sbin/task_manager.pl.in
  t/parse_templates.t
Labels: enhancement

#440 Use tidyall to ease tidying files
  .gitignore
  Makefile.am
  cpanfile
  doc/dot.tidyallrc
  src/bin/p12topem.pl.in
  src/bin/sympa_soap_client.pl.in
  src/bin/sympa_test_ldap.pl.in
  src/bin/tpl2tt2.pl.in
  src/bin/upgrade_bulk_spool.pl.in
  src/bin/upgrade_shared_repository.pl.in
  src/bin/upgrade_sympa_password.pl.in
  src/cgi/sympa_soap_server.fcgi.in
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/DatabaseDriver/ODBC.pm
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Spindle/ProcessOutgoing.pm
  src/lib/Sympa/Tools/DKIM.pm
  src/libexec/ldap_alias_manager.pl.in
  src/libexec/mysql_alias_manager.pl.in
  src/sbin/archived.pl.in
  src/sbin/bounced.pl.in
  src/sbin/bulk.pl.in
  src/sbin/sympa.pl.in
  src/sbin/sympa_automatic.pl.in
  src/sbin/sympa_msg.pl.in
  src/sbin/sympa_newaliases.pl.in
  t/01_Conf.t
  t/02_Sympa_DatabaseManager.t
  t/Language.t
  t/Regexps.t
  t/compile_executables.t
  t/tools_data.t
  t/tools_time.t
  xt/pod-coverage.t
Labels: enhancement

#454 Moving/copying a list, existing list may be overwritten
  src/lib/Sympa/Request/Handler/move_list.pm
Labels: bug

#455 The lists with "bounce" addresses should not be created
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Aliases.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Request/Handler/create_automatic_list.pm
  src/lib/Sympa/Request/Handler/create_list.pm
  src/lib/Sympa/Request/Handler/move_list.pm
Labels: bug
