Repository sympa-community/sympa, pull requests merged in 2018-06, with the labels that each got.

#330 WWSympa: wwsympa_url would be optional
  default/mail_tt2/automatic_bounce_management.tt2
  default/mail_tt2/command_report.tt2
  default/mail_tt2/expire_warning1.tt2
  default/mail_tt2/expire_warning2.tt2
  default/mail_tt2/invite.tt2
  default/mail_tt2/list_created.tt2
  default/mail_tt2/reject.tt2
  default/mail_tt2/remind.tt2
  default/mail_tt2/request_auth.tt2
  default/mail_tt2/user_notification.tt2
  default/mail_tt2/welcome.tt2
  default/mail_tt2/x509-user-cert-missing.tt2
  default/web_tt2/serveradmin.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Conf.pm
  src/lib/Sympa/Archive.pm
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/Upgrade.pm
Labels: enhancement

#332 Support for spam reporting in bulk. Moved the bulk moderation controls.
  default/web_tt2/modindex.tt2
Labels: bug

#336 Starting a test framework
  Makefile.am
  t/01_Conf.t
  t/02_Sympa_DatabaseManager.t
  t/data/etc/auth.conf
  t/data/sympa.conf
  t/data/sympa.sqlite
Labels: test
