Repository sympa-community/sympa, pull requests merged in 2019-08, with the labels that each got.

#645 Allow to activate pending lists with sympa.pl
  src/sbin/sympa.pl.in
Labels: enhancement

#721 WWSympa: send_mail: Restrict MIME content type of uploaded HTML text (#716)
  src/cgi/wwsympa.fcgi.in
Labels: bug

#730 pod2md: Some fixes
  support/pod2md
Labels: packaging
