Repository sympa-community/sympa, pull requests merged in 2019-01, with the labels that each got.

#478 Fix #295 — Add domain blacklist feature
  default/mail_tt2/report.tt2
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Request/Handler/add.pm
  src/lib/Sympa/Request/Handler/subscribe.pm
  src/lib/Sympa/Tools/Domains.pm
Labels: enhancement

#515 A scalar parameter in list config without value is warned
  src/lib/Sympa/List.pm
Labels: bug, on going

#519 `sympa.pl --upgrade_config_location` doesn't respect configured user/group
  src/sbin/sympa.pl.in
Labels: bug, on going

#525 Weaken sympa and wwsympa/sympa soap link
  src/etc/script/sympa-archive.servicein
  src/etc/script/sympa-bounce.servicein
  src/etc/script/sympa-outgoing.servicein
  src/etc/script/sympa-task.servicein
  src/etc/script/sympasoap.servicein
  src/etc/script/wwsympa.servicein
Labels: enhancement

#528 Invalid default scenarios
  default/Makefile.am
  default/web_tt2/config_common.tt2
  src/lib/Sympa.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/ListDef.pm
  src/lib/Sympa/Robot.pm
Labels: bug, design, on going

#534 Mail command unavailable in confirmation requests
  default/mail_tt2/request_auth.tt2
Labels: bug, on going

#541 Owner page is empty
  src/lib/Sympa/List.pm
Labels: bug, on going
