Repository sympa-community/sympa, pull requests merged in 2019-02, with the labels that each got.

#549 exclusion_table might not be updated properly during "sympa.pl --upgrade"
  src/lib/Sympa/Upgrade.pm
Labels: bug, on going

#547 Prepare minimal sympa.conf at install time (cf. #508)
  .gitignore
  Makefile.am
  configure.ac
  sympa.conf.in
Labels: on going

#550 Kill VOOT support
  ext/DEVEL.pm
  ext/NetVOOT/ChangeLog
  ext/NetVOOT/Makefile.PL
  ext/NetVOOT/examples/voot
  ext/NetVOOT/lib/Net/VOOT.pm
  ext/NetVOOT/lib/Net/VOOT/Renater.pm
  ext/NetVOOT/lib/Net/VOOT/SURFconext.pm
  ext/NetVOOT/t/10surfnet.t
  ext/NetVOOT/t/20renater.t
  ext/NetVOOT/xt/99pod.t
  ext/OAuth1C/lib/Sympa/OAuth1/Consumer.pm
  ext/OAuth1C/lib/Sympa/OAuth1/Consumer/Upgrade.pm
  ext/OAuth1C/lib/Sympa/OAuth1/Consumer/Website.pm
  ext/OAuth1P/VOOTProvider.pm
  ext/OAuth1P/lib/Sympa/OAuth1/Provider.pm
  ext/OAuth1P/lib/Sympa/OAuth1/Provider/tt2/oauth_authorize.tt2
  ext/OAuth1P/lib/Sympa/OAuth1/Provider/tt2/oauth_check.tt2
  ext/OAuth1P/lib/Sympa/OAuth1P.pm
  ext/OAuth2C/lib/Sympa/OAuth2/Consumer.pm
  ext/OAuth2C/lib/Sympa/OAuth2/Consumer/Upgrade.pm
  ext/OAuth2C/lib/Sympa/OAuth2/Consumer/Website.pm
  ext/Plugin/lib/Sympa/Plugin.pm
  ext/Plugin/lib/Sympa/Plugin/ListSource.pm
  ext/Plugin/lib/Sympa/Plugin/Manager.pm
  ext/Plugin/lib/Sympa/Plugin/Util.pm
  ext/README
  ext/VOOT/MANIFEST
  ext/VOOT/lib/Sympa/VOOT.pm
  ext/VOOT/lib/Sympa/VOOT/Consumer.pm
  ext/VOOT/lib/Sympa/VOOT/Renater.pod
  ext/VOOT/lib/Sympa/VOOT/SURFconext.pod
  ext/VOOT/lib/Sympa/VOOT/Website.pm
  ext/VOOT/lib/Sympa/VOOT/tt2/help_editlist_voot.tt2
  ext/VOOT/lib/Sympa/VOOT/tt2/list_menu_opensocial.tt2
  ext/VOOT/lib/Sympa/VOOT/tt2/message_report_voot_failed.tt2
  ext/VOOT/lib/Sympa/VOOT/tt2/select_voot_groups_request.tt2
  ext/VOOT/lib/Sympa/VOOT/tt2/select_voot_provider_request.tt2
  ext/VOOT/lib/Sympa/VOOT/tt2/sync_include_voot_failed.tt2
  ext/VOOT/xt/99pod.t
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/ListDef.pm
  t/data/sympa.conf
Labels: design

#552 `bounce_email_prefix` parameter was not considered to prevent reserved addrresses for list name (PR#455)
  src/lib/Sympa/Aliases.pm
  src/lib/Sympa/Family.pm
Labels: bug

#555 WWSympa: Features of archives and shared repository should be able to be disabled
  default/web_tt2/admin.tt2
  default/web_tt2/list_menu.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/Upgrade.pm
Labels: bug
