Repository sympa-community/sympa, pull requests merged in 2019-06, with the labels that each got.

#618 Fix #613 — Avoid MHonArc’s search warning flood
  src/lib/Sympa/WWW/Marc/Search.pm
Labels: bug

#627 Fix #621 — Add a 'gecos' option to web_archive_spam_protection
  src/lib/Sympa/ConfDef.pm
  src/lib/Sympa/HTMLDecorator.pm
  src/lib/Sympa/ListDef.pm
  src/lib/Sympa/ListOpt.pm
Labels: enhancement

#628 Fix message_header and message_footer links not showing in editfile page
  default/web_tt2/editfile.tt2
Labels: bug

#629 Don’t capture extra spaces at the end of line in topics.conf
  src/lib/Sympa/Robot.pm
Labels: bug

#664 Support Test::Compile 2.0.0
  .travis.yml
  cpanfile
  t/compile_executables.t
  t/compile_modules.t
Labels: test

#674 Fix error in subindex.tt2, subscribtions reject button does not work
  default/web_tt2/subindex.tt2
Labels: bug

#638 Make it clear on web interface that a list is being moderated
  default/web_tt2/main.tt2
Labels: design, enhancement

#640 Add « report as spam » option when deleting archives
  default/mhonarc-ressources.tt2
  default/web_tt2/confirm_action.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Spindle/ProcessArchive.pm
Labels: enhancement

#516 Improving data sources
  cpanfile
  default/web_tt2/edit.tt2
  default/web_tt2/subscriber_table.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Makefile.am
  src/lib/Sympa/DataSource.pm
  src/lib/Sympa/DataSource/File.pm
  src/lib/Sympa/DataSource/LDAP.pm
  src/lib/Sympa/DataSource/LDAP2.pm
  src/lib/Sympa/DataSource/List.pm
  src/lib/Sympa/DataSource/RemoteDump.pm
  src/lib/Sympa/DataSource/RemoteFile.pm
  src/lib/Sympa/DataSource/SQL.pm
  src/lib/Sympa/Database.pm
  src/lib/Sympa/DatabaseDescription.pm
  src/lib/Sympa/DatabaseDriver/LDAP.pm
  src/lib/Sympa/Datasource.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/ListDef.pm
  src/lib/Sympa/ListOpt.pm
  src/lib/Sympa/Request.pm
  src/lib/Sympa/Request/Handler/include.pm
  src/lib/Sympa/Request/Handler/move_user.pm
  src/lib/Sympa/Spindle/ProcessTask.pm
  src/lib/Sympa/Upgrade.pm
Labels: bug, design, enhancement
