Repository sympa-community/sympa, pull requests merged in 2019-11, with the labels that each got.

#790 Add option to notify lists’ owners when opening lists from command line
  src/sbin/sympa.pl.in
Labels: enhancement

#787 Various improvements to --sync-include output
  src/sbin/sympa.pl.in
Labels: enhancement

#802 Prevent warning caused by empty description in XML list definition file.
  src/lib/Sympa/Request/Handler/create_list.pm
Labels: bug, on going

#807 Prevent Sympa daemon crash due to a broken plugin module.
  src/lib/Sympa/Message/Plugin.pm
Labels: enhancement

#782 Enhancements on scenarios
  .gitlab-ci.yml
  .travis.yml
  Makefile.am
  default/mail_tt2/listmaster_notification.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Scenario.pm
  t/compile_scenarios.t
Labels: enhancement, on going

#771 Refactor family
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Config_XML.pm
  src/lib/Sympa/Family.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Request/Handler/create_automatic_list.pm
  src/lib/Sympa/Request/Handler/create_list.pm
  src/lib/Sympa/Request/Handler/update_automatic_list.pm
  src/lib/Sympa/Spindle/ProcessAutomatic.pm
  src/lib/Sympa/Upgrade.pm
  src/lib/Sympa/WWW/SOAP.pm
  src/sbin/sympa.pl.in
Labels: on going

#811 Updating dependency Test::Pod
  cpanfile
  t/pod-syntax.t
Labels: bug, test
