Repository sympa-community/sympa, pull requests merged in 2020-05, with the labels that each got.

#933 2 fixes related to list families
  src/lib/Sympa/List.pm
  src/sbin/sympa.pl.in
Labels: bug, enhancement

#925 list index performance update for wwsympa.fcgi do_lists subroutine
  src/cgi/wwsympa.fcgi.in
Labels: enhancement

#936 Typos in set_index() of some DatabaseDriver classes.
  src/lib/Sympa/DatabaseDriver/MySQL.pm
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/DatabaseDriver/SQLite.pm
Labels: bug

#941 Every time users were loaded via include_sql_query Sympa would raise warnings
  src/lib/Sympa/DataSource/SQL.pm
Labels: bug
