Repository sympa-community/sympa, pull requests merged in 2020-11, with the labels that each got.

#1004 Update a dependency MHonArc
  cpanfile
  src/sbin/sympa_wizard.pl.in
Labels: bug

#1022 🐛 — Fix confirmation for reporting as spam while deleting an archived mail
  src/cgi/wwsympa.fcgi.in
Labels: bug, hacktoberfest-accepted

#1025 Show subjects of archived mails before deletion’s confirmation
  default/mhonarc-ressources.tt2
  default/web_tt2/confirm_action.tt2
  default/web_tt2/css.tt2
  src/cgi/wwsympa.fcgi.in
Labels: enhancement, hacktoberfest-accepted

#1015 Add "aliases_wrapper" configuration parameter
  src/lib/Sympa/Aliases/Template.pm
  src/lib/Sympa/Config/Schema.pm
Labels: security
