Repository sympa-community/sympa, pull requests merged in 2020-12, with the labels that each got.

#1040 Additional fix to #946 (#1015)
  src/lib/Sympa/Aliases/Template.pm
Labels: enhancement

#1043 Add proper exit code on errors to SOAP client script.
  src/bin/sympa_soap_client.pl.in
Labels: bug, on going

#1045 Add actual error to the log if connection to LDAP server fails.
  src/lib/Sympa/DatabaseDriver/LDAP.pm
Labels: bug, on going

#1044 Properly check email and session id in authenticateAndRun SOAP call (#1041)
  src/lib/Sympa/WWW/SOAP.pm
Labels: bug, security

#1062 Adjust compose_mail template to the obsolescence of the merge_feature configuration parameter
  default/web_tt2/compose_mail.tt2
Labels: bug
