Repository sympa-community/sympa, pull requests merged in 2021-11, with the labels that each got.

#1267 Fix outdated "intranet" sample in create_list schema description.
  src/lib/Sympa/Config/Schema.pm
Labels: bug

#1271 footer_type no longer omits text/html parts
  po/sympa/ca.po
  po/sympa/de.po
  po/sympa/es.po
  po/sympa/eu.po
  po/sympa/fr.po
  po/sympa/gl.po
  po/sympa/hu.po
  po/sympa/it.po
  po/sympa/ja.po
  po/sympa/oc.po
  po/sympa/ru.po
  po/sympa/sv.po
  po/sympa/sympa.pot
  src/lib/Sympa/Config/Schema.pm
Labels: bug

#1269 Build process: Use configured Perl on "make tidyall"
  Makefile.am
Labels: enhancement

#1251 sympa.pl: Adding a new option --add, and expand --add and --del options
  Makefile.am
  default/edit_list.conf
  default/mail_tt2/report.tt2
  src/cgi/wwsympa.fcgi.in
  src/lib/Makefile.am
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/DataSource.pm
  src/lib/Sympa/Family.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Request/Handler/add.pm
  src/lib/Sympa/Request/Handler/close_list.pm
  src/lib/Sympa/Request/Handler/del.pm
  src/lib/Sympa/Request/Handler/import.pm
  src/lib/Sympa/Request/Handler/include.pm
  src/lib/Sympa/Request/Handler/move_user.pm
  src/lib/Sympa/Request/Handler/signoff.pm
  src/lib/Sympa/Request/Handler/subscribe.pm
  src/lib/Sympa/Spindle/ProcessBounce.pm
  src/lib/Sympa/Spindle/ProcessTask.pm
  src/lib/Sympa/Upgrade.pm
  src/sbin/sympa.pl.in
  t/DataSource_LDAP2.t
  t/Request_Handler_add+del.t
Labels: enhancement, on going

#1279 Config: The warning that password_hash parameter should not be changed is obsoleted (#1277)
  po/sympa/af.po
  po/sympa/ar.po
  po/sympa/bg.po
  po/sympa/br.po
  po/sympa/ca.po
  po/sympa/cs.po
  po/sympa/de.po
  po/sympa/el.po
  po/sympa/en_US.po
  po/sympa/eo.po
  po/sympa/es.po
  po/sympa/et.po
  po/sympa/eu.po
  po/sympa/fi.po
  po/sympa/fr.po
  po/sympa/gl.po
  po/sympa/hr.po
  po/sympa/hu.po
  po/sympa/id.po
  po/sympa/io.po
  po/sympa/it.po
  po/sympa/ja.po
  po/sympa/ko.po
  po/sympa/la.po
  po/sympa/ml.po
  po/sympa/nb.po
  po/sympa/nl.po
  po/sympa/nn.po
  po/sympa/oc.po
  po/sympa/pl.po
  po/sympa/pt.po
  po/sympa/pt_BR.po
  po/sympa/rm.po
  po/sympa/ro.po
  po/sympa/ru.po
  po/sympa/sv.po
  po/sympa/sympa.pot
  po/sympa/tr.po
  po/sympa/vi.po
  po/sympa/zh_CN.po
  po/sympa/zh_TW.po
  src/lib/Sympa/Config/Schema.pm
Labels: bug

#1226 Cleanup: Avoid using bareword filehandles etc.
  src/bin/arc2webarc.pl.in
  src/bin/tpl2tt2.pl.in
  src/bin/upgrade_sympa_password.pl.in
  src/cgi/wwsympa.fcgi.in
  src/lib/Conf.pm
  src/lib/Sympa/Family.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Message/Template.pm
  src/lib/Sympa/Process.pm
  src/lib/Sympa/Request/Handler/create_automatic_list.pm
  src/lib/Sympa/Request/Handler/move_list.pm
  src/lib/Sympa/Request/Handler/update_automatic_list.pm
  src/lib/Sympa/Spindle/ProcessTask.pm
  src/lib/Sympa/Tools/SMIME.pm
  src/lib/Sympa/Upgrade.pm
  src/lib/Sympa/WWW/Tools.pm
  src/libexec/ldap_alias_manager.pl.in
  src/sbin/sympa.pl.in
  src/sbin/sympa_wizard.pl.in
Labels: enhancement, on going
