Repository sympa-community/sympa, pull requests merged in 2021-04, with the labels that each got.

#1133 Skip approval for owner subscription and unsubscription
  default/scenari/subscribe.owner
  default/scenari/unsubscribe.owner
Labels: enhancement

#1143 xgettext.pl: Templates shouldn't be processed as Perl source
  support/xgettext.pl
Labels: bug

#1074 Release 6.2.62
  NEWS.md
Labels: on going

#1140 Add list visibility scenario for logged in users.
  default/scenari/visibility.identified
Labels: enhancement

#1150 Empty paragraph in list config should not be warned.
  src/lib/Sympa/List.pm
Labels: bug

#1152 [-bug] Comments in HTTP Accept-Language field should be omitted
  src/lib/Sympa/Language.pm
Labels: bug
