Repository sympa-community/sympa, pull requests merged in 2021-06, with the labels that each got.

#1189 delete_list_member() failed removing subscribers' pictures
  src/lib/Sympa/List.pm
Labels: bug

#1191 Add create_list.closed scenario.
  default/mail_tt2/report.tt2
  default/scenari/create_list.closed
Labels: enhancement

#1183 Make distribution_ttl and inclusion_notification_feature site-wide
  src/lib/Sympa/Config/Schema.pm
Labels: enhancement

#1188 Release 6.2.64
  NEWS.md
Labels: on going
