Repository sympa-community/sympa, pull requests merged in 2021-05, with the labels that each got.

#1159 Use web URL in instruction if web interface is available
  default/mail_tt2/certif_warning.tt2
  default/mail_tt2/delivery_status_notification.tt2
  default/mail_tt2/expire_deletion.tt2
  default/mail_tt2/expire_warning1.tt2
  default/mail_tt2/expire_warning2.tt2
  default/mail_tt2/global_remind.tt2
  default/mail_tt2/list_unknown.tt2
  default/mail_tt2/listowner_notification.tt2
  default/mail_tt2/moderate.tt2
  default/mail_tt2/removed.tt2
  default/mail_tt2/send_auth.tt2
  src/lib/Sympa/List.pm
Labels: enhancement

#1167 Obsolete escape_chars() / unescape_chars()
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Archive.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Spindle/ProcessTask.pm
  src/lib/Sympa/Tools/Text.pm
  src/lib/Sympa/Tracking.pm
  src/lib/Sympa/Upgrade.pm
Labels: enhancement, on going

#1176 Hide archive download link from users without proper permissions
  default/web_tt2/info.tt2
Labels: enhancement, on going

#1178 Release 6.2.64
  NEWS.md
Labels: on going
