Repository sympa-community/sympa, pull requests merged in 2022-11, with the labels that each got.

#1515 Adding GH workflow to submit the PR for translation
  .github/release.yml
  .github/workflows/make-check.yml
  .github/workflows/submit-pr-for-translation.yml
Labels: translation, on going

#1511 Update `support/xgettext.pl`
  po/sympa/Makevars
  po/sympa/POTFILES.in
  po/sympa/sympa.pot
  po/web_help/Makevars
  po/web_help/web_help.pot
  support/xgettext.pl
Labels: enhancement, translation, on going, packaging

#1449 Following typo fix in Mail::DKIM::ARC::Signer
  cpanfile
  src/lib/Sympa/Message.pm
Labels: bug, on going

#1453 ARC: Add Authentication-Results: field (AR), if useful one is not found
  cpanfile
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Regexps.pm
  src/lib/Sympa/Spindle/ProcessAutomatic.pm
  src/lib/Sympa/Spindle/ProcessIncoming.pm
  src/lib/Sympa/Tools/DKIM.pm
Labels: enhancement, on going

#1457 Forwarded messages should also be ARC sealed if possible
  src/lib/Sympa/Spindle/DoForward.pm
Labels: enhancement, on going

#1456 Import SOAP encoding schema in WSDL
  default/sympa.wsdl
Labels: bug, on going

#1466 WWSyjmpa: Page size cannot be changed on review and reviewbouncing
  default/web_tt2/review.tt2
  default/web_tt2/reviewbouncing.tt2
Labels: bug, on going

#1467 Update SMTP status codes
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/WWW/Tools.pm
Labels: enhancement, on going

#1470 Let some obsoleted parameters be retired and add convenient spam_status scenarios
  default/Makefile.am
  default/scenari/spam_status.bogofilter
  default/scenari/spam_status.j-chkmail
  default/scenari/spam_status.none
  default/scenari/spam_status.rspamd
  default/scenari/spam_status.spamassassin
  default/scenari/spam_status.x-spam-status
  default/web_tt2/modindex.tt2
  doc/sympa_config.podpl
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Config/Schema.pm
Labels: bug, on going

#1502 Update default of anonymous_header_fields parameter
  src/lib/Sympa/Config/Schema.pm
Labels: enhancement, on going

#1503 Improve "set" request handler
  Makefile.am
  default/mail_tt2/report.tt2
  src/lib/Makefile.am
  src/lib/Sympa/CLI/set.pm
  src/lib/Sympa/Request.pm
  src/lib/Sympa/Request/Handler/set.pm
  src/sbin/sympa.pl.in
  t/Request_Handler_set.t
Labels: enhancement, on going

#1508 Use DSN for the message to notify moderation
  default/mail_tt2/delivery_status_notification.tt2
  default/mail_tt2/message_report.tt2
  src/lib/Sympa.pm
  src/lib/Sympa/Spindle/ToEditor.pm
  src/lib/Sympa/Spindle/ToModeration.pm
Labels: enhancement, on going

#1520 Adding translation catalogs for Latvian (lv) by request
  po/sympa/LINGUAS
  po/sympa/lv.po
  po/terminology/io.po
  po/terminology/la.po
  po/terminology/lv.po
  po/terminology/rm.po
  po/web_help/LINGUAS
  po/web_help/lv.po
Labels: enhancement, translation, on going

#1516 Fix SQLite upgrade with lowercase types
  src/lib/Sympa/DatabaseDriver/SQLite.pm
Labels: bug, on going

#1517 Fix various typos in source comments
  NEWS.md
  doc/sympa_config.podpl
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa.pm
  src/lib/Sympa/CLI/show_pending_lists.pm
  src/lib/Sympa/DataSource.pm
  src/lib/Sympa/Family.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Message/Plugin.pm
  src/lib/Sympa/Tools/Data.pm
  src/sbin/sympa.pl.in
  support/xgettext.pl
Labels: bug, on going

#1527 Add --noout option to sympa command line (see #1518)
  src/lib/Sympa/CLI.pm
  src/lib/Sympa/CLI/bouncers/reset.pm
  src/lib/Sympa/CLI/config.pm
  src/lib/Sympa/CLI/dump.pm
  src/lib/Sympa/CLI/lowercase.pm
  src/lib/Sympa/CLI/restore.pm
  src/sbin/sympa.pl.in
Labels: enhancement

#1518 Fix 'sympa config' command return code to be 0 when there are no changes
  src/lib/Sympa/CLI/config.pm
Labels: bug
