Repository sympa-community/sympa, pull requests merged in 2022-01, with the labels that each got.

#1316 🙈 — Update .gitignore
  .gitignore
Labels: enhancement

#1311 Show list names when purging closed lists
  default/web_tt2/confirm_action.tt2
  default/web_tt2/css.tt2
Labels: enhancement

#1320 Improve xgettext.pl
  support/xgettext.pl
Labels: bug

#1260 Release 6.2.68
  NEWS.md
Labels: on going

#1313 Remind name of the opened list in the notification
  default/mail_tt2/report.tt2
  src/lib/Sympa/Request/Handler/open_list.pm
Labels: enhancement

#1328 🚸 — Add anchors to prefs to ease linking (like in FAQ, etc.)
  default/web_tt2/pref.tt2
Labels: enhancement
