Repository sympa-community/sympa, pull requests merged in 2023-02, with the labels that each got.

#1575 Sympa::HTMLSanitizer: Avoid bug in HTML::StripScripts, reDoS with style attribute (#1573)
  Makefile.am
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/HTMLSanitizer.pm
  t/HTMLSanitizer.t
Labels: bug

#1560 Spurious error log during upgrade on removing nonexisting column
  Makefile.am
  src/lib/Sympa/DatabaseDriver.pm
  src/lib/Sympa/DatabaseDriver/MySQL.pm
  src/lib/Sympa/DatabaseDriver/Oracle.pm
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/DatabaseDriver/SQLite.pm
  src/lib/Sympa/DatabaseManager.pm
  src/lib/Sympa/Upgrade.pm
  t/DatabaseManager.t
  t/Database_SQLite.t
  t/data/sympa.conf
  t/data/sympa.sqlite
Labels: bug

#1571 Spurious error log adding subscriber (#1532)
  src/lib/Sympa/User.pm
Labels: bug

#1562 [CVE-2021-4243] Potential XSS in jquery-minicolors (#1561)
  default/web_tt2/head_javascript.tt2
  www/js/jquery-minicolors/jquery.minicolors.css
  www/js/jquery-minicolors/jquery.minicolors.js
  www/js/jquery-minicolors/jquery.minicolors.min.js
Labels: bug, security

#1565 Fix description for add CLI command
  src/lib/Sympa/CLI/add.pm
Labels: bug, ready

#1558 Replace obsolete Ansible role in README
  README.md
Labels: ready

#1556 Update support/sync_translation.sh
  support/sync_translation.sh
Labels: translation, ready

#1587 Update copyright years
  Makefile.am
  src/lib/Sympa/CLI/add.pm
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/DatabaseDriver.pm
  src/lib/Sympa/DatabaseDriver/MySQL.pm
  src/lib/Sympa/DatabaseDriver/Oracle.pm
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/DatabaseDriver/SQLite.pm
  src/lib/Sympa/DatabaseManager.pm
  src/lib/Sympa/Upgrade.pm
  src/lib/Sympa/User.pm
Labels: ready, ignore-for-release

#1596 Adding translation catalogs for Georgian (ka) by request
  po/sympa/LINGUAS
  po/sympa/ka.po
  po/terminology/ka.po
  po/web_help/LINGUAS
  po/web_help/ka.po
Labels: translation
