Repository sympa-community/sympa, pull requests merged in 2023-12, with the labels that each got.

#1712 Can't locate object method "new" via package "Sympa::Aliases" (#1710)
  src/lib/Sympa/Request/Handler/update_automatic_list.pm
Labels: bug, ready

#1698 SOAP: Fix typos in sympa.wsdl
  default/sympa.wsdl
Labels: bug, ready

#1687 🐛 — Fix error when rejecting message from direct URL
  src/cgi/wwsympa.fcgi.in
Labels: bug, security, ready

#1745 Missing validation on Digest frequency in Edit Config (#1742)
  src/lib/Sympa/Config.pm
  src/lib/Sympa/Config/Schema.pm
Labels: bug, ready

#1741 Upgrade command should fail if no previuos version number can be found.
  src/lib/Sympa/CLI/upgrade.pm
Labels: bug, ready

#1734 INFO mail command pulls different owners and/or moderators than those with web UI (#1732)
  src/lib/Sympa/Request/Handler/info.pm
Labels: bug, ready

#1726 DSN with status 4.3.0 may mess the parent of nested list (#1699)
  src/lib/Sympa/Spindle/ToModeration.pm
Labels: bug, ready

#1755 WWSympa: Accessing Navigation Menu, focus go back to Top Bar (#1747)
  default/web_tt2/nav.tt2
Labels: bug, ready

#1701 Tracking: Remove outdated heuristics for bounce processing
  src/lib/Sympa/Spindle/ProcessBounce.pm
Labels: design, ready

#1680 RSS: lastBuildDate element in RSS feed was inproperly formatted
  src/cgi/wwsympa.fcgi.in
Labels: bug, ready

#1666 A workaround for the browser back to let the "Please Wait..." spinner remain
  www/js/sympa.js
Labels: bug, ready

#1662 Manually deleted list blocks closure of the list which has been included by the former (#1660)
  src/lib/Sympa/List.pm
Labels: bug, ready

#1651 "warning: ignoring prerequisites on suffix rule definition" with GNU make 4.3
  service/Makefile.am
  src/libexec/Makefile.am
Labels: bug, ready

#1592 Broken output with SOAP API due to mixture of byte- and utf8-strings (#1541)
  src/cgi/sympa_soap_server.fcgi.in
  src/lib/Makefile.am
  src/lib/Sympa/CLI/test/soap.pm
  src/lib/Sympa/WWW/SOAP.pm
  src/lib/Sympa/WWW/SOAP/FastCGI.pm
Labels: bug, ready

#1579 WWSympa: Save default sort key in review (#1577)
  src/cgi/wwsympa.fcgi.in
Labels: enhancement, ready

#1704 WWSympa: Direct link to reject action crashes
  default/web_tt2/confirm_action.tt2
  src/cgi/wwsympa.fcgi.in
Labels: bug, ready

#1563 WWSympa: Enable autofilling of password only if necessary
  default/web_tt2/choosepasswd.tt2
  default/web_tt2/config_common.tt2
  default/web_tt2/login.tt2
  default/web_tt2/pref.tt2
Labels: bug, ready

#1570 Noise in Apache error_log (#1325)
  default/web_tt2/search_user.tt2
  src/lib/Conf.pm
  src/lib/Sympa/Config.pm
  src/lib/Sympa/List/Users.pm
Labels: bug, ready

#1568 sympa instantiate: Progress bar could not be inactivated
  src/lib/Sympa/CLI/instantiate.pm
  src/sbin/sympa.pl.in
Labels: bug, ready

#1779 WWSympa: Screen Reader needs clear labels for text fields (#1748)
  default/web_tt2/arcsearch_form.tt2
  default/web_tt2/compose_mail.tt2
  default/web_tt2/manage_template.tt2
  default/web_tt2/rss_request.tt2
  default/web_tt2/search_list_request.tt2
  default/web_tt2/serveradmin.tt2
  default/web_tt2/sso_login.tt2
Labels: bug, ready

#1572 Display name in `From:` header field should be quoted / unquoted appropriately
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Tools/Text.pm
Labels: enhancement, ready
