Repository sympa-community/sympa, pull requests merged in 2024-09, with the labels that each got.

#1803 WWSympa: Uploaded file names in UTF-8 were garbled (#1802)
  cpanfile
  src/lib/Sympa/Tools/Text.pm
Labels: bug, ready

#1798 Fix cross-robot list inclusion (#1797)
  src/lib/Sympa/DataSource/List.pm
Labels: enhancement, ready

#1709 🐛 — [moderation] Show message content when clicking on its object
  default/web_tt2/modindex.tt2
Labels: bug, ready

#1813 PostgreSQL/SQLite: Sympa tries creating temporary views in databases unnecessarily (#1812)
  src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
  src/lib/Sympa/DatabaseDriver/SQLite.pm
  src/lib/Sympa/DatabaseManager.pm
  t/Database_SQLite.t
Labels: bug, ready

#1800 Update a dependency MIME-EncWords (#1787)
  cpanfile
Labels: bug, ready

#1818 Stop "do_distribute" actions from Web interface from generating backscatter emails to sympa-request alias (#1737)
  src/cgi/wwsympa.fcgi.in
Labels: bug, ready

#1824 If lock fails, details should be included in the error message
  src/lib/Sympa/Aliases/Template.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Process.pm
  src/lib/Sympa/Request/Handler/update_automatic_list.pm
Labels: bug, ready

#1856 typos
  default/web_tt2/get_inactive_lists.tt2
Labels: ready

#1830 Noise in Apache error_log (again) (#1325)
  src/lib/Conf.pm
  src/lib/Sympa/Aliases.pm
  src/lib/Sympa/List.pm
  src/lib/Sympa/Scenario.pm
Labels: bug, ready

#1865 Expose update_epoch on get_closed_lists.
  default/web_tt2/get_closed_lists.tt2
  src/cgi/wwsympa.fcgi.in
Labels: enhancement, ready

#1831 CLI: With `sympa config key=value`, key couldn't contain dot
  src/lib/Sympa/CLI.pm
Labels: bug, ready

#1832 Debian Bug#1062398 Lacks dependency on `perldoc` utility
  src/lib/Sympa/CLI/help.pm
Labels: bug, ready, packaging

#1844 Prevent custom_header with non-ASCII characters (#1840)
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/Regexps.pm
  src/lib/Sympa/Spindle/TransformOutgoing.pm
Labels: bug, ready

#1845 Incorrect "No bouncing members" on a large list with small number of bouncers (#1842)
  default/web_tt2/reviewbouncing.tt2
Labels: bug, ready

#1885 WWSympa: Invalid UTF-8 sequences in input may trigger crashing (#1884)
  .github/workflows/make-check.yml
  .gitlab-ci.yml
  .travis.yml
  cpanfile
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Tools/Text.pm
  t/Tools_Text.t
Labels: bug, ready

#1841 Parameter for syslog socket should allow options such as host name
  src/cgi/sympa_soap_server.fcgi.in
  src/cgi/wwsympa.fcgi.in
  src/lib/Conf.pm
  src/lib/Sympa/CLI.pm
  src/lib/Sympa/CLI/check.pm
  src/lib/Sympa/CLI/test/syslog.pm
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/Log.pm
  src/lib/Sympa/Spindle/ProcessOutgoing.pm
  src/lib/Sympa/Upgrade.pm
  src/libexec/alias_manager.pl.in
  src/sbin/archived.pl.in
  src/sbin/bounced.pl.in
  src/sbin/bulk.pl.in
  src/sbin/sympa_automatic.pl.in
  src/sbin/sympa_msg.pl.in
  src/sbin/sympa_newaliases.pl.in
  src/sbin/task_manager.pl.in
  sympa.conf.in
  t/Database_SQLite.t
  t/Request_Handler_set.t
Labels: enhancement, ready

#1892 LDAP: Add `deref` option to specify how to dereference aliases
  doc/auth.conf.pod
  src/cgi/wwsympa.fcgi.in
  src/lib/Conf.pm
  src/lib/Sympa/CLI/test/ldap.pm
  src/lib/Sympa/Config/Schema.pm
  src/lib/Sympa/DataSource/LDAP.pm
  src/lib/Sympa/ListOpt.pm
  src/lib/Sympa/Scenario.pm
  src/lib/Sympa/WWW/Auth.pm
Labels: enhancement

#1889 WWSynmpa: do_distribute: Confirmation was not always performed
  src/cgi/wwsympa.fcgi.in
Labels: bug, ready

#1869 Several fixes/improvements on ARC seal & DKIM signature
  src/lib/Sympa/Internals/Workflow.pod
  src/lib/Sympa/Message.pm
  src/lib/Sympa/Spindle/AuthorizeMessage.pm
  src/lib/Sympa/Spindle/DoForward.pm
  src/lib/Sympa/Spindle/ProcessModeration.pm
  src/lib/Sympa/Spindle/ProcessOutgoing.pm
  src/lib/Sympa/Tools/Data.pm
  src/lib/Sympa/Tracking.pm
Labels: bug, enhancement, ready
