Repository sympa-community/sympa, pull requests merged in 2024-08, with the labels that each got.

#1667 WWSympa: Detect web crawlers
  default/Makefile.am
  default/crawlers_detection.conf
  doc/Makefile.am
  doc/crawlers_detection.conf.pod
  doc/sympa_config.podpl
  doc/sympa_toc.pod
  src/cgi/wwsympa.fcgi.in
  src/lib/Conf.pm
  src/lib/Makefile.am
  src/lib/Sympa/WWW/Crawlers.pm
  src/lib/Sympa/WWW/Session.pm
  support/README.support.md
  support/make_crawlers.pl
Labels: enhancement, ready

#1690 Improve diagnostic messages in the DSNs generated by Sympa
  src/lib/Sympa.pm
Labels: enhancement, ready

#1717 DKIM: i= tag may not match in some auto-generated messages (#1716)
  src/lib/Sympa/Tools/DKIM.pm
Labels: bug, ready

#1849 (AB) add an invite feature to WWSympa
  default/web_tt2/import.tt2
  default/web_tt2/review.tt2
  src/cgi/wwsympa.fcgi.in
Labels: enhancement

#1718 Add links to create or recreate password (#1713)
  default/web_tt2/renewpasswd.tt2
  src/cgi/wwsympa.fcgi.in
Labels: bug, ready

#1809 The length of boundary lines in multipart messages could exceed 70 octets (#1795)
  src/lib/Sympa.pm
  src/lib/Sympa/Message/Template.pm
Labels: bug, ready

#1817 Allow "custom_subject" to be at the beginning of the subject (#1811)
  src/lib/Sympa/Spindle/TransformIncoming.pm
  t/Spindle_TransformIncoming.t
Labels: enhancement, ready

#1882 Setting invite sender as From: field should be avoided (#1846)
  default/mail_tt2/invite.tt2
Labels: bug, ready
