Repository sympa-community/sympa, pull requests merged in 2025-05, with the labels that each got.

#1923 Drop support for Perl earlier than 5.26.0 (#1801)
  .github/workflows/make-check.yml
  .gitlab-ci.yml
  .travis.yml
  cpanfile
Labels: design, ready, packaging

#1959 Fix dmarc_protection from address (#1958)
  src/lib/Sympa/Message.pm
Labels: bug, ignore-for-release

#1958 Fix dmarc_protection from address
  src/lib/Sympa/Message.pm
Labels: bug

#1906 Make Unicode::UTF8 mandatory
  .github/workflows/make-check.yml
  .gitlab-ci.yml
  .travis.yml
  cpanfile
  src/cgi/wwsympa.fcgi.in
  src/lib/Sympa/Tools/Text.pm
  t/Tools_Text.t
Labels: ready, packaging

#1902 Giving up Archive-Zip
  cpanfile
  src/cgi/wwsympa.fcgi.in
Labels: ready, packaging
